apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: example-app-1
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: demo-2023
  url: https://github.com/gerundium/flux-demo-apps